2021-10-18 18:06:36,196 INFO    MainThread:989940 [wandb_setup.py:_flush():69] setting env: {}
2021-10-18 18:06:36,197 INFO    MainThread:989940 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-18 18:06:36,197 INFO    MainThread:989940 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'b18955ee7e70b0998e9360e0872ec5228439cf65'}
2021-10-18 18:06:36,197 INFO    MainThread:989940 [wandb_init.py:_log_setup():357] Logging user logs to /home/Pedro/xray_duplicates_detector/wandb/run-20211018_180636-28y73q7o/logs/debug.log
2021-10-18 18:06:36,197 INFO    MainThread:989940 [wandb_init.py:_log_setup():358] Logging internal logs to /home/Pedro/xray_duplicates_detector/wandb/run-20211018_180636-28y73q7o/logs/debug-internal.log
2021-10-18 18:06:36,197 INFO    MainThread:989940 [wandb_init.py:_jupyter_setup():307] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f31321f3ee0>
2021-10-18 18:06:36,197 INFO    MainThread:989940 [wandb_init.py:init():390] calling init triggers
2021-10-18 18:06:36,197 INFO    MainThread:989940 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {'dataset': 'mendeley', 'random_seed': 12, 'batch_size': 128, 'resolution': 256}
2021-10-18 18:06:36,197 INFO    MainThread:989940 [wandb_init.py:init():435] starting backend
2021-10-18 18:06:36,197 INFO    MainThread:989940 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-18 18:06:36,615 INFO    MainThread:989940 [backend.py:ensure_launched():135] starting backend process...
2021-10-18 18:06:36,960 INFO    MainThread:989940 [backend.py:ensure_launched():139] started backend process with pid: 1003232
2021-10-18 18:06:36,962 INFO    MainThread:989940 [wandb_init.py:init():440] backend started and connected
2021-10-18 18:06:36,982 INFO    MainThread:989940 [wandb_run.py:_label_probe_notebook():833] probe notebook
2021-10-18 18:06:36,983 INFO    MainThread:989940 [wandb_run.py:_label_probe_notebook():843] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-10-18 18:06:36,983 INFO    MainThread:989940 [wandb_init.py:init():499] updated telemetry
2021-10-18 18:06:36,984 INFO    MainThread:989940 [wandb_init.py:init():522] communicating current version
2021-10-18 18:06:38,227 INFO    MainThread:989940 [wandb_init.py:init():527] got version response 
2021-10-18 18:06:38,227 INFO    MainThread:989940 [wandb_init.py:init():535] communicating run to backend with 30 second timeout
2021-10-18 18:06:38,615 INFO    MainThread:989940 [wandb_init.py:init():562] starting run threads in backend
2021-10-18 18:06:43,624 INFO    MainThread:989940 [wandb_run.py:_console_start():1651] atexit reg
2021-10-18 18:06:43,624 INFO    MainThread:989940 [wandb_run.py:_redirect():1525] redirect: SettingsConsole.WRAP
2021-10-18 18:06:43,624 INFO    MainThread:989940 [wandb_run.py:_redirect():1562] Wrapping output streams.
2021-10-18 18:06:43,625 INFO    MainThread:989940 [wandb_run.py:_redirect():1586] Redirects installed.
2021-10-18 18:06:43,626 INFO    MainThread:989940 [wandb_init.py:init():587] run started, returning control to user process
2021-10-18 18:07:42,034 INFO    MainThread:989940 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-18 18:07:42,034 INFO    MainThread:989940 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2021-10-18 18:08:30,316 INFO    MainThread:989940 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-18 18:08:30,324 INFO    MainThread:989940 [wandb_setup.py:_flush():69] setting env: {}
2021-10-18 18:08:30,325 INFO    MainThread:989940 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-18 18:08:30,325 INFO    MainThread:989940 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'b18955ee7e70b0998e9360e0872ec5228439cf65'}
2021-10-18 18:08:30,325 INFO    MainThread:989940 [wandb_init.py:_log_setup():357] Logging user logs to /home/Pedro/xray_duplicates_detector/wandb/run-20211018_180830-2rsfgu1z/logs/debug.log
2021-10-18 18:08:30,326 INFO    MainThread:989940 [wandb_init.py:_log_setup():358] Logging internal logs to /home/Pedro/xray_duplicates_detector/wandb/run-20211018_180830-2rsfgu1z/logs/debug-internal.log
2021-10-18 18:08:30,326 INFO    MainThread:989940 [wandb_init.py:init():390] calling init triggers
2021-10-18 18:08:30,326 INFO    MainThread:989940 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {'dataset': 'mendeley', 'random_seed': 12, 'batch_size': 128, 'resolution': 256}
2021-10-18 18:08:30,326 INFO    MainThread:989940 [wandb_init.py:init():410] re-initializing run, found existing run on stack: 28y73q7o
2021-10-18 18:08:30,327 INFO    MainThread:989940 [wandb_run.py:finish():1311] finishing run usp-covid-xrays/xrays/28y73q7o
2021-10-18 18:08:30,514 INFO    MainThread:989940 [jupyter.py:save_history():428] not saving jupyter history
2021-10-18 18:08:30,514 INFO    MainThread:989940 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2021-10-18 18:08:30,514 INFO    MainThread:989940 [wandb_init.py:_jupyter_teardown():289] cleaning up jupyter logic
2021-10-18 18:08:30,515 INFO    MainThread:989940 [wandb_run.py:_atexit_cleanup():1621] got exitcode: 0
2021-10-18 18:08:30,515 INFO    MainThread:989940 [wandb_run.py:_restore():1593] restore
2021-10-18 18:08:30,853 INFO    MainThread:989940 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1027
  total_bytes: 1027
}

2021-10-18 18:08:31,101 INFO    MainThread:989940 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1027
  total_bytes: 1027
}

2021-10-18 18:08:31,269 INFO    MainThread:989940 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 1027
  total_bytes: 7061
}

2021-10-18 18:08:31,372 INFO    MainThread:989940 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1027
  total_bytes: 7189
}

2021-10-18 18:08:31,474 INFO    MainThread:989940 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7189
  total_bytes: 7189
}

2021-10-18 18:08:31,577 INFO    MainThread:989940 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7189
  total_bytes: 7189
}

2021-10-18 18:08:31,679 INFO    MainThread:989940 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7189
  total_bytes: 7189
}

2021-10-18 18:08:31,781 INFO    MainThread:989940 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7189
  total_bytes: 7189
}

2021-10-18 18:08:31,883 INFO    MainThread:989940 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7189
  total_bytes: 7189
}

2021-10-18 18:08:32,280 INFO    MainThread:989940 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7189
  total_bytes: 7189
}

2021-10-18 18:08:32,635 INFO    MainThread:989940 [wandb_run.py:_wait_for_finish():1746] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7189
  total_bytes: 7189
}
local_info {
}

2021-10-18 18:08:33,996 INFO    MainThread:989940 [wandb_run.py:_append_history():1959] rendering history
2021-10-18 18:08:33,996 INFO    MainThread:989940 [wandb_run.py:_append_summary():1914] rendering summary
2021-10-18 18:08:33,996 INFO    MainThread:989940 [wandb_run.py:_append_files():2009] logging synced files
